xprop check

diff --git a/ror b/ror
--- a/ror
+++ b/ror
@@ -4,7 +4,7 @@ show_usage() {
     local cmd=$(basename "${BASH_SOURCE[0]}")
     echo "Usage: $cmd [OPTION]... COMMAND [ARG]...
 
-Jump to (focus) the first open window for an application, if it's running.
+Raise (focus) the first open window for an application, if it's running.
 Otherwise, launch COMMAND (with opitonal ARGs) to start the application.
 
 Options:
@@ -62,11 +62,13 @@ main() {
 
 check_for_prerequisites() {
     if ! has_command wmctrl; then
-        die 'Error: wmctrl(1) can not be found. Please install it to continue.'
+        die 'Error: wmctrl can not be found. Please install it to continue.'
     fi &&
-
-    if [[ -n "$mouse_center" ]] && ! has_command xdotool; then
-        die 'Error: xdotool(1) can not be found. Please install it to use "-C".'
+    if ! has_command xprop; then
+        die 'Error: xprop can not be found. Please install it to continue.'
+    fi &&
+    if ! has_command xdotool; then
+        die 'Error: xdotool can not be found. Please install it to continue.'
     fi
 }
 
